// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBh9tPEcZPbhPGXjnGoN343tS4xsFhjNPI',
    appId: '1:260982386941:web:de77c0a49c1c5aac9a8e94',
    messagingSenderId: '260982386941',
    projectId: 'electionssystem-381414',
    authDomain: 'electionssystem-381414.firebaseapp.com',
    storageBucket: 'electionssystem-381414.appspot.com',
    measurementId: 'G-QL50DL3W9E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6aJ_gRxU15yd39nztjYNAKXKvxXqnils',
    appId: '1:260982386941:android:02b6b6321624c76e9a8e94',
    messagingSenderId: '260982386941',
    projectId: 'electionssystem-381414',
    storageBucket: 'electionssystem-381414.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChyIJqGn6Apao-hpPpfa1tHyBbSrZixfg',
    appId: '1:260982386941:ios:7a69991a6e6c90a39a8e94',
    messagingSenderId: '260982386941',
    projectId: 'electionssystem-381414',
    storageBucket: 'electionssystem-381414.appspot.com',
    iosClientId: '260982386941-tmth75vclvtakm1hsa74m96c49ee7p3r.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalproj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChyIJqGn6Apao-hpPpfa1tHyBbSrZixfg',
    appId: '1:260982386941:ios:7a69991a6e6c90a39a8e94',
    messagingSenderId: '260982386941',
    projectId: 'electionssystem-381414',
    storageBucket: 'electionssystem-381414.appspot.com',
    iosClientId: '260982386941-tmth75vclvtakm1hsa74m96c49ee7p3r.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalproj',
  );
}
